### ISSUE TITLE
Error: unknown node of type "Literal" with constructor "Object"

### ISSUE THREAD

**Issue by Rush** [MatAtBread/fast-async#23]
I wanted to give a `fast-async` a second shot but unfortunately it didn't work. I did nail down the problem to this piece of code though.

```
let foo = async () => {
  for(let bar of []) {
    await Promise.resolve();
  }
};
```

Full error:
```
/code/babel-fast-async-test/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

ReferenceError: /code/babel-fast-async-test/index.js: unknown node of type "Literal" with constructor "Object"
    at Generator.print (/code/babel-fast-async-test/node_modules/babel-generator/lib/printer.js:279:13)
    at Generator.MemberExpression (/code/babel-fast-async-test/node_modules/babel-generator/lib/generators/expressions.js:228:10)
    at /code/babel-fast-async-test/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/code/babel-fast-async-test/node_modules/babel-generator/lib/buffer.js:151:5)
    at Generator.withSource (/code/babel-fast-async-test/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/code/babel-fast-async-test/node_modules/babel-generator/lib/printer.js:297:10)
    at Generator.AssignmentExpression (/code/babel-fast-async-test/node_modules/babel-generator/lib/generators/expressions.js:189:8)
    at /code/babel-fast-async-test/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/code/babel-fast-async-test/node_modules/babel-generator/lib/buffer.js:151:5)
    at Generator.withSource (/code/babel-fast-async-test/node_modules/babel-generator/lib/printer.js:189:15)
```

My `.babelrc`:
```
{
  "presets": ["es2015-node6"],
  "plugins": ["transform-decorators-legacy", "transform-class-properties", "transform-es2015-modules-commonjs", "transform-strict-mode", "transform-es2015-spread", "transform-es2015-destructuring", "transform-es2015-block-scoping", ["fast-async", {
    "compiler": {
      "sourcemap": true
    }
  }]]
}
```

To reproduce:
```
wget http://x.rushbase.net/ad01410a94ea35c0d57d86ddfe4eedd4da29c877/babel-fast-async-test.zip
cd babel-fast-async-test
npm install
node -r babel-register index.js
```

**Comment by matAtWork** [comment]
Fixed by 50415890d29655f829cdc6da1116f2ee60962aa1 (v3.0.7)
